# Generated by Django 4.2.5 on 2023-12-19 08:52

import ValidationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('midleName', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, validators=[ValidationApp.models.validate_email_domain])),
                ('date_of_birth', models.DateField(validators=[ValidationApp.models.validate_age])),
                ('gender', models.CharField(max_length=1, validators=[ValidationApp.models.validate_gender])),
                ('phone', models.CharField(max_length=15, validators=[ValidationApp.models.validate_phone_number])),
                ('referanceNumber', models.PositiveIntegerField(validators=[ValidationApp.models.validate_reference_number])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, validators=[ValidationApp.models.validate_plate_number])),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
