# Generated by Django 4.2.5 on 2023-12-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='midleName',
            new_name='middle_name',
        ),
    ]
